[package]
name = "rendering"
version = "0.1.0"
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geometry3d = {git = "https://github.com/SIMPLE-BuildingSimulation/geometry3d.git"}
# geometry3d = {path = "../geometry3d"}
rand = {version = "0.8.4"}
rayon = {version = "1.5", optional = true}

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
path = "./benches/benchmark.rs"
harness = false

[features]
default = []
float = ["geometry3d/float"]
parallel = ["geometry3d/parallel", "rayon"]


[profile.release]
debug=true
lto = true
codegen-units = 1

