[package]
name = "rendering"
version = "0.1.0"
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geometry3d = {git = "https://github.com/SIMPLE-BuildingSimulation/geometry3d.git"}
rand = "0.8.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
path = "./benches/benchmark.rs"
harness = false

[features]
default = []
float = ["geometry3d/float"]


[profile.release]
lto = true
codegen-units = 1

