name: Docs

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:     
  docs:    
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3     
      - name: Set Toolchain
        run: rustup default nightly    
      - name: Update
        run: rustup update 
      - name: Validate
        run: |
          cargo test --release --package rendering --test validate_ray_tracer -- validate_ray_tracer --exact --nocapture --ignored
          cargo test --release --package rendering --test validate_dc -- validate_dc --exact --nocapture  --ignored
      - name: Build doc
        run: RUSTDOCFLAGS="--html-in-header katex.html" cargo doc --document-private-items --no-deps --target-dir ./docs/rustdoc      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
  
