name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:  
  test:
    build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1   
    - name: Build
      run: cargo test --verbose
  build_float:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo test --verbose --features float   
  build_parallel:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo test --verbose --features parallel
  build_parallel_float:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo test --verbose --features parallel --features float
  build_textures:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo test --verbose --features textures 

  build_textures_float:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo test --verbose --features textures --features textures