name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:  
  test:
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@v1  
    # - uses: taiki-e/install-action@cargo-hack 
    - name: Run tests default
      run: cargo test --verbose     
    - name: Run tests float
      run: cargo test --features float --verbose     
    - name: Run tests float parallel
      run: cargo test --features float --features parallel --verbose    
    - name: Run tests parallel
      run: cargo test --features parallel --verbose     
    - name: Run tests textures
      run: cargo test --features textures --verbose     
    - name: Run tests textures
      run: cargo test --features textures --verbose     
  